baseURL = "https://ospo-ch.github.io/ospo-hugo-theme/"
title = "ospo"
theme = "ospo-hugo-theme"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
[languages.en]
contentDir = "content/en"
languageName = "English"
languageCode = "en-US"
weight = 1

[languages.fr]
contentDir = "content/fr"
languageName = "French"
languageCode = "fr-FR"
weight = 2

[build]
useResourceCacheWhen = "fallback"

[taxonomies]
category = "categories"
tag = "tags"
languages = "languages"

[params]

[params.accessibility]
skip_text = "Skip to content"
help_text = "Accessibility Statement"
help_url = "/example-page/"

# UI configuration
[params.ui]
logo = "images/logo.svg"

[params.links]
[[params.links.user]]
key = "x-twitter"
name = "Twitter"
url = "https://example.org/twitter"
desc = "Follow us on Twitter to get the latest news"
[[params.links.user]]
key = "linkedin"
url = "https://example.org/linkedin"
desc = "Follow us on LinkedIn to get the latest news"
[[params.links.user]]
key = "discord"
name = "Discord"
url = "https://example.org/discord"
desc = "Join our discord channel to get the latest news"
[[params.links.user]]
key = "github"
name = "GitHub"
url = "https://example.org/github"
desc = "Development is happening here"

[menu]

[[menu.main]]
identifier = "software-catalog"
name = "Software Catalog"
url = "catalog/"
weight = 1

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "projects/"
weight = 2

[[menu.main]]
identifier = "insights"
name = "Insights"
url = "insights/"
weight = 3

[[menu.main]]
identifier = "docs"
name = "Docs"
url = "docs/"
weight = 4
